Beloop\Component\Instagram\Entity\Comment:
    type: entity
    table: instagram_comment

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        text:
            column: text
            type: text
            required: true
            nullable: false
        enabled:
            column: enabled
            type: boolean
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: false

    manyToOne:
        image:
            targetEntity: Beloop\Component\Instagram\Entity\Instagram
            inversedBy: comments
            joinColumn:
                name: image_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
                onUpdate: "CASCADE"
        user:
            targetEntity: Beloop\Component\User\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
                onUpdate: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]