Beloop\Component\Instagram\Entity\Instagram:
    type: entity
    repositoryClass: Beloop\Component\Instagram\Repository\InstagramRepository
    table: instagram

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        title:
            column: title
            type: string
            length: 255
            required: true
            nullable: false
        description:
            column: description
            type: text
            required: false
            nullable: true
        imageName:
            column: image_name
            type: string
            length: 255
            nullable: false
        enabled:
            column: enabled
            type: boolean
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: false

    manyToOne:
        user:
            targetEntity: Beloop\Component\User\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
                onUpdate: "CASCADE"
            inversedBy: images

        course:
            targetEntity: Beloop\Component\Course\Entity\Course
            joinColumn:
                name: course_id
                referencedColumnName: id
                nullable: true
                onDelete: "CASCADE"
                onUpdate: "CASCADE"

    oneToMany:
        comments:
            targetEntity: Beloop\Component\Instagram\Entity\Comment
            mappedBy: image

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]