services:

    #
    # Factories
    #

    #
    # Factory for entity instagram
    #
    beloop.factory.instagram:
        class: Beloop\Component\Instagram\Factory\InstagramFactory
        calls:
            - [setEntityNamespace, ["%beloop.entity.instagram.class%"]]

    #
    # Factory for entity instagram comment
    #
    beloop.factory.instagram_comment:
        class: Beloop\Component\Instagram\Factory\CommentFactory
        calls:
            - [setEntityNamespace, ["%beloop.entity.instagram_comment.class%"]]